version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mmongodb+srv://johnsmith2001it:twFDF2QLX9uQ5fbt@cluster0.troet70.mongodb.net/test
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=datasearch
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - cluster.initial_master_nodes=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
    networks:
      - node-network
    volumes:
      - elasticdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    ports:
      - '5601:5601'
    networks:
      - node-network

volumes:
  dbdata:
  elasticdata:

networks:
  node-network:
    driver: bridge
# version: '3'

# services:
#   node-app:
#     build: .
#     image: node-app
#     environment:
#       - MONGODB_URL=mmongodb+srv://johnsmith2001it:twFDF2QLX9uQ5fbt@cluster0.troet70.mongodb.net/test
#     ports:
#       - '3000:3000'
#     depends_on:
#       - mongodb
#       - logstash
#     volumes:
#       - .:/usr/src/node-app
#     networks:
#       - node-network

#   mongodb:
#     image: mongo:4.2.1-bionic
#     ports:
#       - '27017:27017'
#     volumes:
#       - dbdata:/data/db
#     networks:
#       - node-network

#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
#     container_name: elasticsearch
#     environment:
#       - node.name=elasticsearch
#       - cluster.name=datasearch
#       - bootstrap.memory_lock=true
#       - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
#       - cluster.initial_master_nodes=elasticsearch
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     ports:
#       - '9200:9200'
#     networks:
#       - node-network
#     volumes:
#       - elasticdata:/usr/share/elasticsearch/data

#   kibana:
#     image: docker.elastic.co/kibana/kibana:7.0.1
#     ports:
#       - '5601:5601'
#     networks:
#       - node-network

#   logstash:
#     image: docker.elastic.co/logstash/logstash:7.0.1
#     volumes:
#       - ./logstash/pipeline:/usr/share/logstash/pipeline/
#     environment:
#       - "XPACK_MONITORING_ENABLED=false"
#     ports:
#       - "5044:5044"
#     depends_on:
#       - elasticsearch
#       - mongodb
#     networks:
#       - node-network

#   filebeat:
#     image: docker.elastic.co/beats/filebeat:7.0.1
#     user: root
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
#     depends_on:
#       - logstash
#     networks:
#       - node-network

# volumes:
#   dbdata:
#   elasticdata:

# networks:
#   node-network:
#     driver: bridge

# # Logstash service
#     logstash:
#         container_name: logstash-01
#         volumes:
#             - /Users/theara/project/docker compose/es kb/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
#             - /Users/theara/project/docker compose/es kb/logstash.yaml:/usr/share/logstash/config/logstash.yml:ro
#         image: 'docker.elastic.co/logstash/logstash:7.16.3'
#         depends_on:
#              kibana-01:
#                condition: service_healthy
#         networks:
#             - elastic

# # Filebeat service
#     filebeat:
#         user: root
#         container_name: filebeat-01
#         command: --strict.perms=false
#         volumes:
#             - /Users/theara/project/docker compose/es kb/filebeat.docker.yaml:/usr/share/filebeat/filebeat.yml:ro
#             - /var/lib/docker/containers:/var/lib/docker/containers:ro
#             - /var/run/docker.sock:/var/run/docker.sock:ro
#         image: 'docker.elastic.co/beats/filebeat:7.16.3'
#         depends_on:
#              kibana-01:
#                condition: service_healthy
#         networks:
#             - elastic
