#### Build node_modules
FROM node:19-alpine as builder

RUN mkdir -p /app \
    && chown -R node:node /app

WORKDIR /app 

COPY --chown=node:node package.json yarn.lock /app/
RUN yarn install --no-lockfile


### Build app
FROM node:19-alpine
RUN mkdir -p /app \
    && chown -R node:node /app

WORKDIR /app

USER node

COPY --from=builder --chown=node:node /app/node_modules /app/node_modules
COPY --chown=node:node . .
